export UPSTREAM_DIR=upstream
export UPSTREAM_REPO=https://github.com/PolyMC/meta-upstream.git
export PMC_DIR=polymc
export PMC_REPO=https://github.com/PolyMC/meta-polymc.git
export BRANCH=master
export DEPLOY_TO_S3=false
export DEPLOY_TO_FOLDER=false
export DEPLOY_FOLDER=/app/public/v1
export DEPLOY_FOLDER_USER=http
export DEPLOY_FOLDER_GROUP=http
export DEPLOY_TO_GIT=false
# export GIT_SSH_COMMAND="ssh -i '${BASEDIR}/config/deploy.key'"
# export GIT_AUTHOR_NAME="Herpington Derpson"
# export GIT_AUTHOR_EMAIL="herpderp@derpmail.com"
# export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
# export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
